### ISSUE TITLE
Follow buttons, like buttons

### ISSUE THREAD

**Issue by stereosteve** [stereosteve/poolparty#4]
- User can follow a soundcloud user in browse mode
- User can like the currently playing track

**Comment by andrewrk** [comment]
also download button for current song, if applicable.

**Comment by stereosteve** [comment]
Like / unlike button (or "favorite" in soundcloud parlance) done: https://github.com/stereosteve/poolparty/commit/cace71d93ff75588710dea999ca4a6a0fc28ff9f
